services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jjp3
      POSTGRES_PASSWORD: BAtFitFMA13#*
      POSTGRES_DB: surface_clean_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./app
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --reload
    volumes:
      - ./app:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
    restart: always

  # frontend:
  #   working_dir: /app
  #   build:
  #     context: ./front
  #   volumes:
  #     - ./front:/app
  #   command: npm run dev
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development

volumes:
  pgdata: