version: "3.8"
services:
  backend:
    build:
      context: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    working_dir: /app
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development